apps/shares/urls.py
from django.conf.urls import url, patterns

from .views import (ShareListView, ShareUpdateView, ShareDetailView, GroupDetailView,
                    GroupCreateView, GroupListView, GroupDeleteView, GroupUpdateView)

urlpatterns = patterns(
    '',
    url(r'^$', ShareListView.as_view(), name='share-list'),
    url(r'^update/(?P<pk>[\w-]+)$', ShareUpdateView.as_view(), name='share-update'),
    url(r'^detail/(?P<pk>[\w-]+)$', ShareDetailView.as_view(), name='share-detail'),
    url(r'^groups/list$', GroupListView.as_view(), name='group-list'),
    url(r'^groups/create$', GroupCreateView.as_view(), name='group-create'),
    url(r'^groups/update/(?P<pk>[\w-]+)$', GroupUpdateView.as_view(), name='group-update'),
    url(r'^groups/delete/(?P<pk>[\w-]+)$', GroupDeleteView.as_view(), name='group-delete'),
    url(r'^groups/detail/(?P<pk>[\w-]+)$', GroupDetailView.as_view(), name='group-detail'),
)

urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.contrib.auth import views

from apps.shares import urls as shares_urls
from apps.shares import api_urls as shares_api_urls
from apps.stats import urls as stats_urls
from apps.updater import urls as updater_urls
from apps.tasks import urls as tasks_urls
from apps.gains import urls as gains_urls
from apps.correlations import urls as correlations_urls

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^api-auth/', include('rest_framework.urls', namespace='rest_framework')),

    url(r'^accounts/login/$', views.login),
    url(r'^accounts/logout/$', views.logout, {'next_page': '/'}),

    # applications
    url(r'^$', include(gains_urls, namespace='gains')),
    url(r'^shares/', include(shares_urls, namespace='shares')),
    url(r'^api/', include(shares_api_urls, namespace='api-shares')),
    url(r'^updater/', include(updater_urls, namespace='updater')),
    url(r'^stats/', include(stats_urls, namespace='stats')),
    url(r'^tasks/', include(tasks_urls, namespace='tasks')),
    url(r'^correlations/', include(correlations_urls, namespace='correlations')),
]

apps/shares/models.py
from django.db import models


class ShareManager(models.Manager):

    @classmethod
    def get_records(cls, share):
        if type(share) != Share:
            raise TypeError("type 'Share' expected")
        return ShareRecord.objects.filter(share__pk=share.pk)

    @classmethod
    def get_groups(cls, share):
        if type(share) != Share:
            raise TypeError("type 'Share' expected")
        return share.sharegroup_set.all()


class Share(models.Model):
    name = models.CharField(max_length=32, db_index=True, unique=True)
    verbose_name = models.CharField(max_length=64, null=True, blank=True)
    updated_daily = models.BooleanField(default=False)
    last_updated = models.DateTimeField(null=True)
    first_record = models.DateField(null=True)
    last_record = models.DateField(null=True)
    num_records = models.PositiveIntegerField(null=True)

    objects = ShareManager()

    class Meta:
        get_latest_by = 'last_updated'

    def __str__(self):
        return self.verbose_name if self.verbose_name else self.name


class ShareSet(models.Model):
    shares = models.ManyToManyField(Share)


class ShareRecord(models.Model):
    share = models.ForeignKey(Share, null=False, db_index=True, related_name='records')
    date = models.DateField(null=False, db_index=True)
    open = models.FloatField(null=False)
    close = models.FloatField(null=False)
    high = models.FloatField(null=False)
    low = models.FloatField(null=False)
    volume = models.FloatField(null=False)

    class Meta:
        unique_together = ('share', 'date',)
        index_together = ['share', 'date']


class ShareGroup(models.Model):
    name = models.CharField(max_length=32, db_index=True, unique=True)
    verbose_name = models.CharField(max_length=64, null=True)
    shares = models.ManyToManyField(Share, blank=True)

    def __str__(self):
        return self.verbose_name if self.verbose_name else self.name

apps/shares/forms.py
from .models import ShareGroup, Share
from django import forms


class ShareGroupForm(forms.ModelForm):
    class Meta:
        model = ShareGroup
        fields = ['verbose_name', 'shares']

    def __init__(self, *args, **kwargs):
        super(ShareGroupForm, self).__init__(*args, **kwargs)
        self.fields['shares'].widget = forms.widgets.CheckboxSelectMultiple()
        self.fields['shares'].queryset = Share.objects.all()

apps/shares/updater/views.py
from django.shortcuts import render
from django.http import JsonResponse
from django.contrib.auth.decorators import login_required
from .updater import Updater


@login_required
def updater_status(request):
    Updater()
    return render(request, 'shares/updater/status.html', {})


@login_required
def updater_status_api(request):
    data = Updater().get_update_status()
    return JsonResponse(data)


@login_required
def full_import(request):
    Updater().update_whole_database()
    return render(request, 'shares/updater/update.html', {})

apps/shares/views.py
from django.views.generic.list import ListView
from django.views.generic.detail import DetailView
from django.views.generic.edit import CreateView, DeleteView, UpdateView
from django.core.urlresolvers import reverse_lazy

from braces.views import LoginRequiredMixin

from utils.views import SortableListView
from .models import Share, ShareGroup
from .forms import ShareGroupForm


class ShareListView(LoginRequiredMixin, SortableListView):
    model = Share
    template_name = 'shares/share_list.html'
    sort_by = ['name', 'records', 'first_record', 'last_record']
    default_sort_by = '-last_record'


class ShareUpdateView(LoginRequiredMixin, UpdateView):
    model = Share
    template_name = 'shares/share_update.html'
    fields = ['verbose_name', 'updated_daily']
    success_url = reverse_lazy('shares:share-list')


class ShareDetailView(LoginRequiredMixin, DetailView):
    model = Share
    template_name = 'shares/share_detail.html'


class GroupListView(LoginRequiredMixin, ListView):
    model = ShareGroup
    template_name = 'shares/groups/group_list.html'


class GroupCreateView(LoginRequiredMixin, CreateView):
    model = ShareGroup
    form_class = ShareGroupForm
    template_name = 'shares/groups/group_form.html'
    success_url = reverse_lazy('shares:group-list')


class GroupDeleteView(LoginRequiredMixin, DeleteView):
    model = ShareGroup
    template_name = 'shares/groups/group_delete.html'
    success_url = reverse_lazy('shares:group-list')


class GroupUpdateView(LoginRequiredMixin, UpdateView):
    model = ShareGroup
    form_class = ShareGroupForm
    template_name = 'shares/groups/group_update.html'
    success_url = reverse_lazy('shares:group-list')


class GroupDetailView(LoginRequiredMixin, DetailView):
    model = ShareGroup
    template_name = 'shares/groups/group_form.html'

templates/shares/groups/group_delete.html
{% extends 'navbar.html' %}

{% block headertext %}Delete share group{% endblock headertext %}
{% block content %}
    <form class="form-horizontal well" action="" method="post">
        {% csrf_token %}
        <p>Are you sure you want to delete share group "{{ object }}"?</p>
        <input type="submit" value="Delete" class="btn btn-danger" />
    </form>
{% endblock %}

templates/shares/groups/group_detail.html
{% extends 'navbar.html' %}

{% block headertext %}Share group <u>{{ sharegroup }}</u>{% endblock headertext %}
{% block content %}
    <a href="{% url 'shares:group-update' sharegroup.pk %}" class="btn btn-info">Edit</a>
    <a href="{% url 'shares:group-delete' sharegroup.pk %}" class="btn btn-danger">Delete</a>
    <dl class="dl-horizontal">
        <dt>Group name:</dt>
        <dd>{{ sharegroup }}</dd>
        <dt>Database name:</dt>
        <dd>{{ sharegroup.name }}</dd>
    </dl>
    <dl class="dl-horizontal">
        <dt>Shares:</dt>
        <dd>
            <ul>
            {% for share in sharegroup.shares.all %}
                <li><a href="{% url 'shares:share-detail' share.pk %}">{{ share }}</a></li>
            {% endfor %}
            </ul>
        </dd>
    </dl>

{% endblock %}

templates/shares/groups/group_form.html
{% extends 'navbar.html' %}
{% load widget_tweaks %}

{% block headertext %}Update share group: {{ form.instance.name }}{% endblock headertext %}
{% block content %}
    <div class="col-sm-6 col-md-4 col-md-offset-4">
        <form class="form-horizontal well" method="post" action="">
            {% csrf_token %}
            {% render_field form.verbose_name placeholder="Group visible name" class+="form-control" %}
            {{ form.name.errors }}
            {% render_field form.shares %}
            <button class="btn btn-lg btn-primary btn-block" type="submit">Update</button>
        </form>
    </div>
{% endblock %}

templates/shares/groups/group_list.html
{% extends 'navbar.html' %}

{% block headertext %}Share groups{% endblock headertext %}
{% block content %}
    <a href="{% url 'shares:group-create' %}" class="btn btn-success"><span class="glyphicon glyphicon-plus"></span>Create group</a>
    {% if object_list %}
    <table class="table table-bordered">
        <thead>
            <tr>
                <th>Name</th>
                <th>Database name</th>
                <th>Shares</th>
                <th>Update</th>
                <th>Delete</th>
            </tr>
        </thead>
        <tbody>
        {% for group in object_list %}
            <tr>
                <td>{{ group }}</td>
                <td>{{ group.name }}</td>
                <td>
                    {% for share in group.shares.all %}
                        {% if forloop.counter <= 3 %}
                            <p>{{ share }}</p>
                        {% elif forloop.counter == 4 and group.shares.all|length > 4 %}
                            <p><a href="{% url 'shares:group-detail' group.pk %}">Show all</a></p>
                        {% endif %}
                    {% endfor %}
                </td>
                <td><a href="{% url 'shares:group-update' group.pk %}" class="btn btn-block btn-info">Edit</a></td>
                <td><a href="{% url 'shares:group-delete' group.pk %}" class="btn btn-block btn-danger">Delete</a></td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
    {% else %}
        <ul><li>No Groups yet.</li></ul>
    {% endif %}
{% endblock %}

templates/shares/groups/group_update.html
{% extends 'navbar.html' %}
{% load widget_tweaks %}

{% block headertext %}Update share group: {{ form.instance.name }}{% endblock headertext %}
{% block content %}
    <div class="col-sm-6 col-md-4 col-md-offset-4">
        <form class="form-horizontal well" method="post" action="">
            {% csrf_token %}
            {% render_field form.visible_name placeholder="Group visible name" class+="form-control" %}
            {{ form.name.errors }}
            {% render_field form.shares class+="form-control" %}
            <button class="btn btn-lg btn-primary btn-block" type="submit">Update</button>
        </form>
    </div>
{% endblock %}