apps/correlations/urls.py
from django.conf.urls import patterns, url

from .views import CorrelationListView, CorrelationSetCreateView, CorrelationSetListView, \
    CorrelationSetUpdateView, CorrelationSetDeleteView


urlpatterns = patterns(
    '',
    url('^correlation-list/$', CorrelationListView.as_view(), name='correlation-list'),
    url('^correlation-set-create/$', CorrelationSetCreateView.as_view(), name='correlation-set-create'),
    url('^correlation-set-list/$', CorrelationSetListView.as_view(), name='correlation-set-list'),
    url('^correlation-set-update/(?P<pk>[\w-]+)$', CorrelationSetUpdateView.as_view(), name='correlation-set-update'),
    url('^correlation-set-delete/(?P<pk>[\w-]+)$', CorrelationSetDeleteView.as_view(), name='correlation-set-delete'),
)

apps/shares/urls.py
from django.conf.urls import url, patterns

from .views import (ShareListView, ShareUpdateView, ShareDetailView, GroupDetailView,
                    GroupCreateView, GroupListView, GroupDeleteView, GroupUpdateView)

urlpatterns = patterns(
    '',
    url(r'^$', ShareListView.as_view(), name='share-list'),
    url(r'^update/(?P<pk>[\w-]+)$', ShareUpdateView.as_view(), name='share-update'),
    url(r'^detail/(?P<pk>[\w-]+)$', ShareDetailView.as_view(), name='share-detail'),
    url(r'^groups/list$', GroupListView.as_view(), name='group-list'),
    url(r'^groups/create$', GroupCreateView.as_view(), name='group-create'),
    url(r'^groups/update/(?P<pk>[\w-]+)$', GroupUpdateView.as_view(), name='group-update'),
    url(r'^groups/delete/(?P<pk>[\w-]+)$', GroupDeleteView.as_view(), name='group-delete'),
    url(r'^groups/detail/(?P<pk>[\w-]+)$', GroupDetailView.as_view(), name='group-detail'),
)

urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.contrib.auth import views

from apps.shares import urls as shares_urls
from apps.shares import api_urls as shares_api_urls
from apps.stats import urls as stats_urls
from apps.updater import urls as updater_urls
from apps.tasks import urls as tasks_urls
from apps.gains import urls as gains_urls
from apps.correlations import urls as correlations_urls

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^api-auth/', include('rest_framework.urls', namespace='rest_framework')),

    url(r'^accounts/login/$', views.login),
    url(r'^accounts/logout/$', views.logout, {'next_page': '/'}),

    # applications
    url(r'^$', include(gains_urls, namespace='gains')),
    url(r'^shares/', include(shares_urls, namespace='shares')),
    url(r'^api/', include(shares_api_urls, namespace='api-shares')),
    url(r'^updater/', include(updater_urls, namespace='updater')),
    url(r'^stats/', include(stats_urls, namespace='stats')),
    url(r'^tasks/', include(tasks_urls, namespace='tasks')),
    url(r'^correlations/', include(correlations_urls, namespace='correlations')),
]

apps/correlations/models.py
from django.db import models
from apps.shares.models import Share, ShareGroup


class Correlation(models.Model):
    input_shares = models.ForeignKey(Share, related_name='+')
    output_share = models.ForeignKey(Share, related_name='+')
    day_interval = models.PositiveSmallIntegerField()
    value = models.FloatField()


class CorrelationSet(models.Model):
    name = models.CharField(max_length=32)
    shares = models.ManyToManyField(Share, related_name='+', blank=True)
    day_interval_start = models.SmallIntegerField()
    day_interval_end = models.SmallIntegerField()
    from_date = models.DateField()

apps/correlations/forms.py
from django import forms

from .models import CorrelationSet
from apps.shares.models import ShareGroup


class CorrelationSetForm(forms.ModelForm):

    share_groups = forms.MultipleChoiceField(choices=((i, i.name) for i in ShareGroup.objects.all()), required=False)
    min_share_length = forms.IntegerField(min_value=0)

    class Meta:
        model = CorrelationSet
        fields = '__all__'

    def save(self, commit=True):
        # TODO
        return super(CorrelationSetForm, self).save(commit)

apps/correlations/views.py
from django.views.generic import CreateView, ListView, UpdateView, DeleteView
from django.core.urlresolvers import reverse_lazy
from braces.views import LoginRequiredMixin

from utils.views import SortableListView
from .models import Correlation, CorrelationSet
from .forms import CorrelationSetForm


class CorrelationListView(LoginRequiredMixin, SortableListView):
    model = Correlation
    sort_by = ['value', 'day_interval']
    default_sort_by = 'value'


class CorrelationSetCreateView(LoginRequiredMixin, CreateView):
    model = CorrelationSet
    form_class = CorrelationSetForm
    success_url = reverse_lazy('correlations:correlation-set-list')


class CorrelationSetListView(LoginRequiredMixin, ListView):
    model = CorrelationSet
    fields = ['name', 'shares']
    template_name = 'correlations/correlationset_list.html'


class CorrelationSetUpdateView(LoginRequiredMixin, UpdateView):
    model = CorrelationSet
    form_class = CorrelationSetForm
    success_url = reverse_lazy('correlations:correlation-set-list')


class CorrelationSetDeleteView(LoginRequiredMixin, DeleteView):
    model = CorrelationSet
    success_url = reverse_lazy('correlations:correlation-set-list')

templates/correlations/correlation_list.html
{% extends 'navbar.html' %}

{% block headertext %}Correlations sets{% endblock headertext %}
{% block content %}
    {% if object_list %}
    <table class="table table-striped table-bordered table-hover">
        <thead>
            <tr>
                <th>{% include 'utils/sort_by.html' with name='Name' sort_by='name' %}</th>
                <th>{% include 'utils/sort_by.html' with name='Record' sort_by='records' %}</th>
                <th>{% include 'utils/sort_by.html' with name='First record' sort_by='first_record' %}</th>
                <th>{% include 'utils/sort_by.html' with name='Last record' sort_by='last_record' %}</th>
                <th>Input shares</th>
                <th>{% include 'utils/sort_by.html' with name='Output share' sort_by='last_record' %}</th>
            </tr>
        </thead>
        <tbody>
        {% for share in object_list %}
            <tr>
                <td><a href="{% url 'shares:share-detail' share.pk %}">{{ share }}</a></td>
                <td>{{ share.records }}</td>
                <td>{{ share.first_record }}</td>
                <td>{{ share.last_record }}</td>
                <td><a href="{% url 'shares:share-update' share.pk %}" class="btn btn-block btn-info">Edit</a></td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
    {% else %}
        <ul><li>No Correlations sets yet.</li></ul>
    {% endif %}
{% endblock %}

templates/correlations/correlationset_form.html
{% extends 'navbar.html' %}
{% load widget_tweaks %}

{% block headertext %}Create Correlation set{% endblock headertext %}
{% block extra_scripts %}
<script src="https://code.jquery.com/ui/1.11.4/jquery-ui.min.js"></script>
<script type="application/javascript">
$(document).ready(function() {
    $('.datepicker').datepicker();
});
</script>
{% endblock extra_scripts %}
{% block content %}
    <div class="col-sm-10 col-md-10 col-md-offset-1">
        <form class="form-horizontal well" method="post" action="">
            {% csrf_token %}
            <div class="form-group">
                <div class="col-sm-4">{{ form.name.label }}</div>
                <div class="col-sm-8">{% render_field form.name class+="form-control" %}</div>
                {{ form.name.errors }}
            </div>
            <div class="form-group">
                <div class="col-sm-4">{{ form.shares.label }}</div>
                <div class="col-sm-8">{% render_field form.shares class+="form-control" %}</div>
                {{ form.shares.errors }}
            </div>
            <div class="form-group">
                <div class="col-sm-4">{{ form.share_groups.label }}</div>
                <div class="col-sm-8">{% render_field form.share_groups class+="form-control" %}</div>
                {{ form.share_groups.errors }}
            </div>
            <div class="form-group">
                <div class="col-sm-4">{{ form.day_interval_start.label }}</div>
                <div class="col-sm-8">{% render_field form.day_interval_start class+="form-control" %}</div>
                {{ form.day_interval_start.errors }}
            </div>
            <div class="form-group">
                <div class="col-sm-4">{{ form.day_interval_end.label }}</div>
                <div class="col-sm-8">{% render_field form.day_interval_end class+="form-control" %}</div>
                {{ form.day_interval_end.errors }}
            </div>
            <div class="form-group">
                <div class="col-sm-4">{{ form.from_date.label }}</div>
                <div class="col-sm-8">{% render_field form.from_date class+="form-control datepicker" %}</div>
                {{ form.from_date.errors }}
            </div>
            <div class="form-group">
                <div class="col-sm-4">{{ form.min_share_length.label }}</div>
                <div class="col-sm-8">{% render_field form.min_share_length class+="form-control" %}</div>
                {{ form.min_share_length.errors }}
            </div>

            <button class="btn btn-lg btn-primary btn-block" type="submit">Create</button>
        </form>
    </div>
{% endblock %}

templates/correlations/correlationset_list.html
{% extends 'navbar.html' %}

{% block headertext %}Correlations{% endblock headertext %}
{% block content %}
    {% if object_list %}
    <table class="table table-striped table-bordered table-hover">
        <thead>
            <tr>
                <th>{% include 'utils/sort_by.html' with name='Name' sort_by='name' %}</th>
                <th>{% include 'utils/sort_by.html' with name='Interval days start' sort_by='day_interval_start' %}</th>
                <th>{% include 'utils/sort_by.html' with name='Interval days end' sort_by='day_interval_end' %}</th>
                <th>{% include 'utils/sort_by.html' with name='From date' sort_by='from_date' %}</th>
                <th>Edit</th>
                <th>Delete</th>
            </tr>
        </thead>
        <tbody>
        {% for correlation_set in object_list %}
            <tr>
                <td>{{ correlation_set.name }}</td>
                <td>{{ correlation_set.day_interval_start }}</td>
                <td>{{ correlation_set.day_interval_end }}</td>
                <td>{{ correlation_set.from_date }}</td>
                <td><a href="{% url 'correlations:correlation-set-update' correlation_set.pk %}" class="btn btn-block btn-info">Edit</a></td>
                <td><a href="{% url 'correlations:correlation-set-delete' correlation_set.pk %}" class="btn btn-block btn-danger">Delete</a></td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
    {% else %}
        <ul><li>No Correlations yet.</li></ul>
    {% endif %}
{% endblock %}