apps/shares/urls.py
from django.conf.urls import url, patterns

from .views import (ShareListView, ShareUpdateView, ShareDetailView, GroupDetailView,
                    GroupCreateView, GroupListView, GroupDeleteView, GroupUpdateView)

urlpatterns = patterns(
    '',
    url(r'^$', ShareListView.as_view(), name='share-list'),
    url(r'^update/(?P<pk>[\w-]+)$', ShareUpdateView.as_view(), name='share-update'),
    url(r'^detail/(?P<pk>[\w-]+)$', ShareDetailView.as_view(), name='share-detail'),
    url(r'^groups/list$', GroupListView.as_view(), name='group-list'),
    url(r'^groups/create$', GroupCreateView.as_view(), name='group-create'),
    url(r'^groups/update/(?P<pk>[\w-]+)$', GroupUpdateView.as_view(), name='group-update'),
    url(r'^groups/delete/(?P<pk>[\w-]+)$', GroupDeleteView.as_view(), name='group-delete'),
    url(r'^groups/detail/(?P<pk>[\w-]+)$', GroupDetailView.as_view(), name='group-detail'),
)

apps/stats/urls.py
from django.conf.urls import url, patterns

from .views import general_info, cpu_info, memory_info, network_info, cpu_load, network_traffic

urlpatterns = patterns(
    '',
    url(r'^$', general_info, name='general'),
    url(r'^cpu/$', cpu_info, name='cpu'),
    url(r'^memory/$', memory_info, name='memory'),
    url(r'^network/$', network_info, name='network'),
    url(r'^cpu/api/$', cpu_load, name='api-cpu'),
    url(r'^network/api/$', network_traffic, name='api-network'),
)

apps/tasks/urls.py
from django.conf.urls import patterns, url
from .views import TaskTaskStatusListView, TaskStatusDeleteView


urlpatterns = patterns(
    '',
    url(r'^list/$', TaskTaskStatusListView.as_view(), name='task-list'),
    # url(r'^create-correlation-task/$', CorrelationTaskCreateView.as_view(), name='correlation-task-create'),
    url(r'^delete/(?P<pk>[\w-]+)$', TaskStatusDeleteView.as_view(), name='task-delete'),
)

apps/updater/urls.py
from django.conf.urls import url, patterns

from .views import updater_status, updater_status_api, import_whole_view, import_few_last_view

urlpatterns = patterns(
    '',
    url(r'^$', updater_status, name='status'),
    url(r'^import-db/$', import_whole_view, name='import-db'),
    url(r'^import-few-last/$', import_few_last_view, name='import-few-last'),
    url(r'^api/$', updater_status_api, name='status-api'),
)

urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.contrib.auth import views

from apps.shares import urls as shares_urls
from apps.shares import api_urls as shares_api_urls
from apps.stats import urls as stats_urls
from apps.updater import urls as updater_urls
from apps.tasks import urls as tasks_urls
from apps.gains import urls as gains_urls
from apps.correlations import urls as correlations_urls

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^api-auth/', include('rest_framework.urls', namespace='rest_framework')),

    url(r'^accounts/login/$', views.login),
    url(r'^accounts/logout/$', views.logout, {'next_page': '/'}),

    # applications
    url(r'^$', include(gains_urls, namespace='gains')),
    url(r'^shares/', include(shares_urls, namespace='shares')),
    url(r'^api/', include(shares_api_urls, namespace='api-shares')),
    url(r'^updater/', include(updater_urls, namespace='updater')),
    url(r'^stats/', include(stats_urls, namespace='stats')),
    url(r'^tasks/', include(tasks_urls, namespace='tasks')),
    url(r'^correlations/', include(correlations_urls, namespace='correlations')),
]

templates/base.html
{% load staticfiles %}

<!DOCTYPE html>
<html lang="en">
    <head>
        <title>{% block title %}Janusze Biznesu{% endblock title %}</title>

        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">

        {% block scripts %}
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootswatch/3.3.4/slate/bootstrap.min.css">

        <script src="http://code.jquery.com/jquery-2.1.4.min.js"></script>
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js"></script>
        {% endblock scripts %}
        {% block extra_scripts %}
        {% endblock extra_scripts %}

        <link rel="shortcut icon" href="{% static 'favicon.png' %}">
    </head>
    <body>
        {% block navbar %}{% endblock navbar %}
        <div class="container">
            <h2>
                {% block headertext %}{% endblock headertext %}
            </h2>
            <hr>
            {% block content %}{% endblock content %}
        </div>
    </body>
</html>

templates/navbar.html
{% extends 'base.html' %}
{% load staticfiles %}

{% block navbar %}
<nav class="navbar navbar-default">
    <div class="container-fluid">
        <div class="navbar-header">
            <a class="navbar-brand" href="/">
                Grustein & Hurnberg
            </a>
        </div>

        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
            <ul class="nav navbar-nav">
                <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
                        Stock exchange<span class="caret"></span>
                    </a>
                    <ul class="dropdown-menu">
                        <li><a href="{% url 'updater:status' %}">Update</a></li>
                        <li><a href="{% url 'shares:share-list' %}">Shares</a></li>
                        <li><a href="{% url 'shares:group-list' %}">Share groups</a></li>
                    </ul>
                </li>
                <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
                        Tasks<span class="caret"></span></a>
                    <ul class="dropdown-menu">
                        <li><a href="{% url 'tasks:task-list' %}">Status</a></li>
                        <li><a href="{# url 'tasks:correlation-task-create' #}">Create correlation</a></li>
                    </ul>
                </li>

                <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
                        Correlations<span class="caret"></span></a>
                    <ul class="dropdown-menu">
                        <li><a href="{% url 'correlations:correlation-list' %}">List</a></li>
                        <li><a href="{% url 'correlations:correlation-set-create' %}">Create correlation set</a></li>
                        <li><a href="{% url 'correlations:correlation-set-list' %}">Correlation set list</a></li>
                    </ul>
                </li>

                <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
                        Statistics<span class="caret"></span></a>
                    <ul class="dropdown-menu">
                        <li><a href="{% url 'stats:general' %}">General</a></li>
                        <li><a href="{% url 'stats:cpu' %}">CPU</a></li>
                        <li><a href="{% url 'stats:memory' %}">Memory</a></li>
                        <li><a href="{% url 'stats:network' %}">Network</a></li>
                    </ul>
                </li>
            </ul>

            <ul class="nav navbar-nav navbar-right">
                <li><a href="#">Settings</a></li>
                <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Hello {{ user.username }}<span class="caret"></span></a>
                    <ul class="dropdown-menu">
                        <li><a href="{% url 'django.contrib.auth.views.logout' %}">Logout</a></li>
                    </ul>
                </li>
            </ul>
        </div><!-- /.navbar-collapse -->
    </div><!-- /.container-fluid -->
</nav>
{% endblock navbar %}